language: java
jdk:
  - openjdk7
  - oraclejdk8
install: 
  - cd src
before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx512m"
env:
  - SPARK_VERSION=1.5
  - SPARK_VERSION=1.6
script:
  - mvn clean package -q -Dmaven.javadoc.skip=true -Dspark${SPARK_VERSION} -DMR2
